language: ruby
services:
- docker
before_install:
- docker build -t agranado2k/book_app .
- docker run -d agranado2k/book_app
- docker ps -a
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
- bundle exec rspec
- bundle exec brakeman -A
- bundle exec bundle audit
- bundle exec rubocop
deploy:
  provider: heroku
  app: thawing-crag-46147
  api_key:
    secure: OFTDlopHmy4/DoKeMtIf1obWlv+SdrkIBS2dNbYJeMeJc3QKJ6JellwklmhUGn/6zjaZ/XyX+lCeqrVbYLwnfQj3w+wVu+eWv8Hz7kKVI1fPE9qcSr4kNgDowXBlsHuTKTI+iitT3AyA2QRruWXnF60/JTSJ5OqWjLpM9u68to2HfJe7B0E/GHrUB26tYJt0PAdX88t9ybpjmGUBG7ZGRnDb9AbcfKuc3/4wJ6FBiSfNKeP7eLItMmwFTOg8LtVfm2AXvMGKJIZUhWrFHnSYVqHNtH8hGQunpr60CZu8JaCkbn+NP9+Gmk/eIJk5pM7kYxoNr8zAjokPYxwBq4ecZWn/25NFUCr5Kjn1DsH+74xbKtMPlMxrTQZqTp5DHNDPsxps7MqL8ftBVFZrAt3+lElBa1Lru1g2sqtmUtlkjwsrbQgqq19cuSJHGbawdSwm7l5dqZGkLGTiOfwfx9TF0/1SeZ3pECdYyqZNctqqt3rBqQfsfXGMTvA+ns+e2ddqG6AyeDU1EhtW8NcsNsPs3pdsaXBqVn/UZtPTvDm7F9S9MRlcJYRa1rVzqR7xlRcO91MRtwxBLZEpHDxdWYZdjWYdnic3jNq6mT2xWF1Np0x7xoTbDewCyRi2CcuqqYNZ/QQYSUs4SKdlGuOLosUqmOvZJc1T0nTWhjbVXbnM5xs=
env:
  secure: DdTknoc3EupcuJn+4yvtU3Fm0uQJer16cyRf6GlnROBvCEQQH7kpbthI4gIjJNKafRitqifpdNbO9GslulLbHumLxoTsHFvj6hKZIBVVOjW4OITHN5Vcp/DUZw5Md7Z16zaviBGYpGiGfyICSDIjn98XR05h9DK9mKbsdoENY4g5tw3rjXNp64vMCAhRO9eM8dms8RrSHwiOEfhWyjMO9dZN4lLfSOUaGKFSYuzA0j/3ji4ppUylU8VoRcBTTMXEqte/oT0qGgLl1bz69bgPCgjVsi9HivzP/sGRpfQs6r0yjjj5/JUCkK1ndjrXlWPzP9oaQe8umy2EEjg8ENcoHky/uEOzuyVuErF2PuaV+SqaS45c0FqbSQq4YMNsZQemaigCqY1e+KdSmtzEWPDE0bKlkWY5KQ4ei5KNBreuHQ5mVu8FA5KjuJIuzFEiLoapYxqDxuYCZgyi1RQamujbGzCMolJ7Vp2++q2JDYs5vJHZCUn2lWfhIvT1V1jT0LCToqdXHd9AdkwnPVobkkLc63RksjEHe3lGCA8CegQ+bnUQKVxaoAb5WtYHINjDq7XARjmQ9rHHWNZ+gfNx+OzrcBGuUTX6tfQjYBC6zNdiB8l8pQ9iqRtu7MXniqTGAbCeVJgWFMAspBcSGAHRBfm2ipkiANt94Q9i5zpXEWGlIFc=
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
