language: ruby
services:
- docker
before_install:
- docker build -t agranado2k/book_app .
- docker run -d agranado2k/book_app
- docker ps -a
script:
- bundle exec rspec
- bundle exec brakeman -A
- bundle exec bundle audit
- bundle exec rubocop
deploy:
  provider: heroku
  app: thawing-crag-46147
  api_key:
    secure: OFTDlopHmy4/DoKeMtIf1obWlv+SdrkIBS2dNbYJeMeJc3QKJ6JellwklmhUGn/6zjaZ/XyX+lCeqrVbYLwnfQj3w+wVu+eWv8Hz7kKVI1fPE9qcSr4kNgDowXBlsHuTKTI+iitT3AyA2QRruWXnF60/JTSJ5OqWjLpM9u68to2HfJe7B0E/GHrUB26tYJt0PAdX88t9ybpjmGUBG7ZGRnDb9AbcfKuc3/4wJ6FBiSfNKeP7eLItMmwFTOg8LtVfm2AXvMGKJIZUhWrFHnSYVqHNtH8hGQunpr60CZu8JaCkbn+NP9+Gmk/eIJk5pM7kYxoNr8zAjokPYxwBq4ecZWn/25NFUCr5Kjn1DsH+74xbKtMPlMxrTQZqTp5DHNDPsxps7MqL8ftBVFZrAt3+lElBa1Lru1g2sqtmUtlkjwsrbQgqq19cuSJHGbawdSwm7l5dqZGkLGTiOfwfx9TF0/1SeZ3pECdYyqZNctqqt3rBqQfsfXGMTvA+ns+e2ddqG6AyeDU1EhtW8NcsNsPs3pdsaXBqVn/UZtPTvDm7F9S9MRlcJYRa1rVzqR7xlRcO91MRtwxBLZEpHDxdWYZdjWYdnic3jNq6mT2xWF1Np0x7xoTbDewCyRi2CcuqqYNZ/QQYSUs4SKdlGuOLosUqmOvZJc1T0nTWhjbVXbnM5xs=
