# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     command: build
    #     dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    - task: SnykSecurityScan@0
      displayName: Snyk scan
      inputs:
        serviceConnectionEndpoint: 'Snyk Token'
        testType: 'container'
        dockerImageName: 'agranadosnyk/book_api:0.0.1'
        dockerfilePath: 'Dockerfile'
        monitorOnBuild: false
        failOnIssues: false
        projectName: 'Azure Test'
